//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GARbro.GUI.Strings {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class guiStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal guiStrings() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GARbro.GUI.Strings.guiStrings", typeof(guiStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 _Abort 的當地語系化字串。
        /// </summary>
        public static string ButtonAbort {
            get {
                return ResourceManager.GetString("ButtonAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Apply 的當地語系化字串。
        /// </summary>
        public static string ButtonApply {
            get {
                return ResourceManager.GetString("ButtonApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cancel 的當地語系化字串。
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 _Continue 的當地語系化字串。
        /// </summary>
        public static string ButtonContinue {
            get {
                return ResourceManager.GetString("ButtonContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Convert 的當地語系化字串。
        /// </summary>
        public static string ButtonConvert {
            get {
                return ResourceManager.GetString("ButtonConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 _Download 的當地語系化字串。
        /// </summary>
        public static string ButtonDownload {
            get {
                return ResourceManager.GetString("ButtonDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Extract 的當地語系化字串。
        /// </summary>
        public static string ButtonExtract {
            get {
                return ResourceManager.GetString("ButtonExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 OK 的當地語系化字串。
        /// </summary>
        public static string ButtonOK {
            get {
                return ResourceManager.GetString("ButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 _Overwrite 的當地語系化字串。
        /// </summary>
        public static string ButtonOverwrite {
            get {
                return ResourceManager.GetString("ButtonOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 _Rename 的當地語系化字串。
        /// </summary>
        public static string ButtonRename {
            get {
                return ResourceManager.GetString("ButtonRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 _Skip 的當地語系化字串。
        /// </summary>
        public static string ButtonSkip {
            get {
                return ResourceManager.GetString("ButtonSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 _Close 的當地語系化字串。
        /// </summary>
        public static string CtxMenuClose {
            get {
                return ResourceManager.GetString("CtxMenuClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Convert multimedia... 的當地語系化字串。
        /// </summary>
        public static string CtxMenuConvert {
            get {
                return ResourceManager.GetString("CtxMenuConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Copy 的當地語系化字串。
        /// </summary>
        public static string CtxMenuCopy {
            get {
                return ResourceManager.GetString("CtxMenuCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Create archive... 的當地語系化字串。
        /// </summary>
        public static string CtxMenuCreate {
            get {
                return ResourceManager.GetString("CtxMenuCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cut 的當地語系化字串。
        /// </summary>
        public static string CtxMenuCut {
            get {
                return ResourceManager.GetString("CtxMenuCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 _Delete 的當地語系化字串。
        /// </summary>
        public static string CtxMenuDelete {
            get {
                return ResourceManager.GetString("CtxMenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Browse in _Explorer 的當地語系化字串。
        /// </summary>
        public static string CtxMenuExplorer {
            get {
                return ResourceManager.GetString("CtxMenuExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Extract 的當地語系化字串。
        /// </summary>
        public static string CtxMenuExtract {
            get {
                return ResourceManager.GetString("CtxMenuExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Assign file type 的當地語系化字串。
        /// </summary>
        public static string CtxMenuFileType {
            get {
                return ResourceManager.GetString("CtxMenuFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Open 的當地語系化字串。
        /// </summary>
        public static string CtxMenuOpen {
            get {
                return ResourceManager.GetString("CtxMenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Paste 的當地語系化字串。
        /// </summary>
        public static string CtxMenuPaste {
            get {
                return ResourceManager.GetString("CtxMenuPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Refresh 的當地語系化字串。
        /// </summary>
        public static string CtxMenuRefresh {
            get {
                return ResourceManager.GetString("CtxMenuRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 _Rename 的當地語系化字串。
        /// </summary>
        public static string CtxMenuRename {
            get {
                return ResourceManager.GetString("CtxMenuRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Select files by mask... 的當地語系化字串。
        /// </summary>
        public static string CtxMenuSelectByMask {
            get {
                return ResourceManager.GetString("CtxMenuSelectByMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Sort by 的當地語系化字串。
        /// </summary>
        public static string CtxMenuSortBy {
            get {
                return ResourceManager.GetString("CtxMenuSortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Name 的當地語系化字串。
        /// </summary>
        public static string CtxMenuSortByName {
            get {
                return ResourceManager.GetString("CtxMenuSortByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Size 的當地語系化字串。
        /// </summary>
        public static string CtxMenuSortBySize {
            get {
                return ResourceManager.GetString("CtxMenuSortBySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Type 的當地語系化字串。
        /// </summary>
        public static string CtxMenuSortByType {
            get {
                return ResourceManager.GetString("CtxMenuSortByType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Unsorted 的當地語系化字串。
        /// </summary>
        public static string CtxMenuUnsorted {
            get {
                return ResourceManager.GetString("CtxMenuUnsorted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Name 的當地語系化字串。
        /// </summary>
        public static string HeaderName {
            get {
                return ResourceManager.GetString("HeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Size 的當地語系化字串。
        /// </summary>
        public static string HeaderSize {
            get {
                return ResourceManager.GetString("HeaderSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Type 的當地語系化字串。
        /// </summary>
        public static string HeaderType {
            get {
                return ResourceManager.GetString("HeaderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 A_pply to all duplicate files 的當地語系化字串。
        /// </summary>
        public static string LabelApplyToAll {
            get {
                return ResourceManager.GetString("LabelApplyToAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Archive format 的當地語系化字串。
        /// </summary>
        public static string LabelArchiveFormat {
            get {
                return ResourceManager.GetString("LabelArchiveFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Archive name 的當地語系化字串。
        /// </summary>
        public static string LabelArchiveName {
            get {
                return ResourceManager.GetString("LabelArchiveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Archive options 的當地語系化字串。
        /// </summary>
        public static string LabelArchiveOptions {
            get {
                return ResourceManager.GetString("LabelArchiveOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Destination directory 的當地語系化字串。
        /// </summary>
        public static string LabelDestinationDir {
            get {
                return ResourceManager.GetString("LabelDestinationDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Choose destination format for images 的當地語系化字串。
        /// </summary>
        public static string LabelDestinationFormat {
            get {
                return ResourceManager.GetString("LabelDestinationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Development site 的當地語系化字串。
        /// </summary>
        public static string LabelDevSite {
            get {
                return ResourceManager.GetString("LabelDevSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 What should be done? 的當地語系化字串。
        /// </summary>
        public static string LabelDuplicateFileQuestion {
            get {
                return ResourceManager.GetString("LabelDuplicateFileQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Encoding 的當地語系化字串。
        /// </summary>
        public static string LabelEncoding {
            get {
                return ResourceManager.GetString("LabelEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Enter wildcard mask 的當地語系化字串。
        /// </summary>
        public static string LabelEnterMask {
            get {
                return ResourceManager.GetString("LabelEnterMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Extract files from {0} to 的當地語系化字串。
        /// </summary>
        public static string LabelExtractAllTo {
            get {
                return ResourceManager.GetString("LabelExtractAllTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Extract {0} to 的當地語系化字串。
        /// </summary>
        public static string LabelExtractFileTo {
            get {
                return ResourceManager.GetString("LabelExtractFileTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 _Ignore further errors 的當地語系化字串。
        /// </summary>
        public static string LabelIgnoreErrors {
            get {
                return ResourceManager.GetString("LabelIgnoreErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Release notes 的當地語系化字串。
        /// </summary>
        public static string LabelReleaseNotes {
            get {
                return ResourceManager.GetString("LabelReleaseNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Skip incovertible files. 的當地語系化字串。
        /// </summary>
        public static string LabelSkipFailures {
            get {
                return ResourceManager.GetString("LabelSkipFailures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 About Game Resource browser 的當地語系化字串。
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 _Check for updates... 的當地語系化字串。
        /// </summary>
        public static string MenuCheckUpdates {
            get {
                return ResourceManager.GetString("MenuCheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 E_xit 的當地語系化字串。
        /// </summary>
        public static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 _File 的當地語系化字串。
        /// </summary>
        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fit preview _window to image 的當地語系化字串。
        /// </summary>
        public static string MenuFitWindow {
            get {
                return ResourceManager.GetString("MenuFitWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 _Help 的當地語系化字串。
        /// </summary>
        public static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Open... 的當地語系化字串。
        /// </summary>
        public static string MenuOpen {
            get {
                return ResourceManager.GetString("MenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 _Preferences 的當地語系化字串。
        /// </summary>
        public static string MenuPreferences {
            get {
                return ResourceManager.GetString("MenuPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Recent files 的當地語系化字串。
        /// </summary>
        public static string MenuRecent {
            get {
                return ResourceManager.GetString("MenuRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Show/hide main _menu bar 的當地語系化字串。
        /// </summary>
        public static string MenuToggleMenuBar {
            get {
                return ResourceManager.GetString("MenuToggleMenuBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Show/hide _status bar 的當地語系化字串。
        /// </summary>
        public static string MenuToggleStatusBar {
            get {
                return ResourceManager.GetString("MenuToggleStatusBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Show/hide _toolbar 的當地語系化字串。
        /// </summary>
        public static string MenuToggleToolBar {
            get {
                return ResourceManager.GetString("MenuToggleToolBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 _View 的當地語系化字串。
        /// </summary>
        public static string MenuView {
            get {
                return ResourceManager.GetString("MenuView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Choose files to extract 的當地語系化字串。
        /// </summary>
        public static string MsgChooseFiles {
            get {
                return ResourceManager.GetString("MsgChooseFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Are you sure you want to delete these files? 的當地語系化字串。
        /// </summary>
        public static string MsgConfirmDeleteFiles {
            get {
                return ResourceManager.GetString("MsgConfirmDeleteFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Converting file {0} 的當地語系化字串。
        /// </summary>
        public static string MsgConvertingFile {
            get {
                return ResourceManager.GetString("MsgConvertingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Creating archive {0} 的當地語系化字串。
        /// </summary>
        public static string MsgCreatingArchive {
            get {
                return ResourceManager.GetString("MsgCreatingArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Deleted {0} 的當地語系化字串。
        /// </summary>
        public static string MsgDeletedItem {
            get {
                return ResourceManager.GetString("MsgDeletedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Deleted {0} file 的當地語系化字串。
        /// </summary>
        public static string MsgDeletedItems1 {
            get {
                return ResourceManager.GetString("MsgDeletedItems1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Deleted {0} files 的當地語系化字串。
        /// </summary>
        public static string MsgDeletedItems2 {
            get {
                return ResourceManager.GetString("MsgDeletedItems2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 directory not found 的當地語系化字串。
        /// </summary>
        public static string MsgDirectoryNotFound {
            get {
                return ResourceManager.GetString("MsgDirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Update download failed. 的當地語系化字串。
        /// </summary>
        public static string MsgDownloadFailed {
            get {
                return ResourceManager.GetString("MsgDownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 archive is empty 的當地語系化字串。
        /// </summary>
        public static string MsgEmptyArchive {
            get {
                return ResourceManager.GetString("MsgEmptyArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Error extracting file 的當地語系化字串。
        /// </summary>
        public static string MsgErrorExtracting {
            get {
                return ResourceManager.GetString("MsgErrorExtracting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Error opening file 的當地語系化字串。
        /// </summary>
        public static string MsgErrorOpening {
            get {
                return ResourceManager.GetString("MsgErrorOpening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Extracted {0} into {1} 的當地語系化字串。
        /// </summary>
        public static string MsgExtractComplete {
            get {
                return ResourceManager.GetString("MsgExtractComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Extracted {0} file 的當地語系化字串。
        /// </summary>
        public static string MsgExtractedFiles1 {
            get {
                return ResourceManager.GetString("MsgExtractedFiles1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Extracted {0} files 的當地語系化字串。
        /// </summary>
        public static string MsgExtractedFiles2 {
            get {
                return ResourceManager.GetString("MsgExtractedFiles2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Extracting files from {0} 的當地語系化字串。
        /// </summary>
        public static string MsgExtractingArchive {
            get {
                return ResourceManager.GetString("MsgExtractingArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Extracting file from {0} 的當地語系化字串。
        /// </summary>
        public static string MsgExtractingFile {
            get {
                return ResourceManager.GetString("MsgExtractingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Extracting files from {0} to {1} 的當地語系化字串。
        /// </summary>
        public static string MsgExtractingTo {
            get {
                return ResourceManager.GetString("MsgExtractingTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} file 的當地語系化字串。
        /// </summary>
        public static string MsgFiles1 {
            get {
                return ResourceManager.GetString("MsgFiles1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} files 的當地語系化字串。
        /// </summary>
        public static string MsgFiles2 {
            get {
                return ResourceManager.GetString("MsgFiles2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Image {0} x {1} x {2}bpp [{3}] 的當地語系化字串。
        /// </summary>
        public static string MsgImageSize {
            get {
                return ResourceManager.GetString("MsgImageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 no files to extract 的當地語系化字串。
        /// </summary>
        public static string MsgNoFiles {
            get {
                return ResourceManager.GetString("MsgNoFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No entries matching &quot;{0}&quot; 的當地語系化字串。
        /// </summary>
        public static string MsgNoMatching {
            get {
                return ResourceManager.GetString("MsgNoMatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No media files selected. 的當地語系化字串。
        /// </summary>
        public static string MsgNoMediaFiles {
            get {
                return ResourceManager.GetString("MsgNoMediaFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No updates currently available. 的當地語系化字串。
        /// </summary>
        public static string MsgNoUpdates {
            get {
                return ResourceManager.GetString("MsgNoUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 File {0}
        ///already exists.
        ///
        ///Overwrite? 的當地語系化字串。
        /// </summary>
        public static string MsgOverwrite {
            get {
                return ResourceManager.GetString("MsgOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Playing {0} / {3} / {2}bps / {1}Hz 的當地語系化字串。
        /// </summary>
        public static string MsgPlaying {
            get {
                return ResourceManager.GetString("MsgPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Ready 的當地語系化字串。
        /// </summary>
        public static string MsgReady {
            get {
                return ResourceManager.GetString("MsgReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} file added to selection 的當地語系化字串。
        /// </summary>
        public static string MsgSelectedFiles1 {
            get {
                return ResourceManager.GetString("MsgSelectedFiles1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} files added to selection 的當地語系化字串。
        /// </summary>
        public static string MsgSelectedFiles2 {
            get {
                return ResourceManager.GetString("MsgSelectedFiles2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 unable to interpret audio format 的當地語系化字串。
        /// </summary>
        public static string MsgUnableInterpretAudio {
            get {
                return ResourceManager.GetString("MsgUnableInterpretAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 unable to interpret image format 的當地語系化字串。
        /// </summary>
        public static string MsgUnableInterpretImage {
            get {
                return ResourceManager.GetString("MsgUnableInterpretImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Formats database update available. 的當地語系化字串。
        /// </summary>
        public static string MsgUpdateAvailable {
            get {
                return ResourceManager.GetString("MsgUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Formats database updated. 的當地語系化字串。
        /// </summary>
        public static string MsgUpdateComplete {
            get {
                return ResourceManager.GetString("MsgUpdateComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Update check failed. 的當地語系化字串。
        /// </summary>
        public static string MsgUpdateFailed {
            get {
                return ResourceManager.GetString("MsgUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 GARbro version is up to date. 的當地語系化字串。
        /// </summary>
        public static string MsgUpToDate {
            get {
                return ResourceManager.GetString("MsgUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Version {0} 的當地語系化字串。
        /// </summary>
        public static string MsgVersion {
            get {
                return ResourceManager.GetString("MsgVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Archives 的當地語系化字串。
        /// </summary>
        public static string TextAboutArchives {
            get {
                return ResourceManager.GetString("TextAboutArchives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Audio 的當地語系化字串。
        /// </summary>
        public static string TextAboutAudio {
            get {
                return ResourceManager.GetString("TextAboutAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 [builtin] 的當地語系化字串。
        /// </summary>
        public static string TextAboutBuiltin {
            get {
                return ResourceManager.GetString("TextAboutBuiltin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Images 的當地語系化字串。
        /// </summary>
        public static string TextAboutImages {
            get {
                return ResourceManager.GetString("TextAboutImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 License 的當地語系化字串。
        /// </summary>
        public static string TextAboutLicense {
            get {
                return ResourceManager.GetString("TextAboutLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 About Game Resource browser 的當地語系化字串。
        /// </summary>
        public static string TextAboutTitle {
            get {
                return ResourceManager.GetString("TextAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 All Files 的當地語系化字串。
        /// </summary>
        public static string TextAllFiles {
            get {
                return ResourceManager.GetString("TextAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 as is 的當地語系化字串。
        /// </summary>
        public static string TextAsIs {
            get {
                return ResourceManager.GetString("TextAsIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Audio will be converted to either WAV, MP3 or OGG. 的當地語系化字串。
        /// </summary>
        public static string TextAudioConversion {
            get {
                return ResourceManager.GetString("TextAudioConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Choose archive location 的當地語系化字串。
        /// </summary>
        public static string TextChooseArchive {
            get {
                return ResourceManager.GetString("TextChooseArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Choose destination directory 的當地語系化字串。
        /// </summary>
        public static string TextChooseDestDir {
            get {
                return ResourceManager.GetString("TextChooseDestDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Confirm overwrite 的當地語系化字串。
        /// </summary>
        public static string TextConfirmOverwrite {
            get {
                return ResourceManager.GetString("TextConfirmOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Convert audio to common format 的當地語系化字串。
        /// </summary>
        public static string TextConvertAudio {
            get {
                return ResourceManager.GetString("TextConvertAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Media conversion 的當地語系化字串。
        /// </summary>
        public static string TextConvertMedia {
            get {
                return ResourceManager.GetString("TextConvertMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Create archive 的當地語系化字串。
        /// </summary>
        public static string TextCreateArchive {
            get {
                return ResourceManager.GetString("TextCreateArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Archive creation error 的當地語系化字串。
        /// </summary>
        public static string TextCreateArchiveError {
            get {
                return ResourceManager.GetString("TextCreateArchiveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Delete files 的當地語系化字串。
        /// </summary>
        public static string TextDeleteFiles {
            get {
                return ResourceManager.GetString("TextDeleteFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Text encoding 的當地語系化字串。
        /// </summary>
        public static string TextEncoding {
            get {
                return ResourceManager.GetString("TextEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Error occured while converting file
        ///{0}
        ///{1} 的當地語系化字串。
        /// </summary>
        public static string TextErrorConverting {
            get {
                return ResourceManager.GetString("TextErrorConverting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Error occured while extracting file
        ///{0}
        ///{1} 的當地語系化字串。
        /// </summary>
        public static string TextErrorExtracting {
            get {
                return ResourceManager.GetString("TextErrorExtracting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Extract audio 的當地語系化字串。
        /// </summary>
        public static string TextExtractAudio {
            get {
                return ResourceManager.GetString("TextExtractAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Extract images 的當地語系化字串。
        /// </summary>
        public static string TextExtractImages {
            get {
                return ResourceManager.GetString("TextExtractImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 File extraction error 的當地語系化字串。
        /// </summary>
        public static string TextExtractionError {
            get {
                return ResourceManager.GetString("TextExtractionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Extract text 的當地語系化字串。
        /// </summary>
        public static string TextExtractText {
            get {
                return ResourceManager.GetString("TextExtractText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Extract from archive 的當地語系化字串。
        /// </summary>
        public static string TextExtractTitle {
            get {
                return ResourceManager.GetString("TextExtractTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 File {0} already exists in the destination folder. 的當地語系化字串。
        /// </summary>
        public static string TextFileAlreadyExists {
            get {
                return ResourceManager.GetString("TextFileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Formats 的當地語系化字串。
        /// </summary>
        public static string TextFormats {
            get {
                return ResourceManager.GetString("TextFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Multimedia conversion error 的當地語系化字串。
        /// </summary>
        public static string TextMediaConvertError {
            get {
                return ResourceManager.GetString("TextMediaConvertError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 New version available: 的當地語系化字串。
        /// </summary>
        public static string TextNewVersion {
            get {
                return ResourceManager.GetString("TextNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Archive parameters 的當地語系化字串。
        /// </summary>
        public static string TextParametersTitle {
            get {
                return ResourceManager.GetString("TextParametersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Preferences 的當地語系化字串。
        /// </summary>
        public static string TextPreferences {
            get {
                return ResourceManager.GetString("TextPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Save as 的當地語系化字串。
        /// </summary>
        public static string TextSaveAs {
            get {
                return ResourceManager.GetString("TextSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Save images as 的當地語系化字串。
        /// </summary>
        public static string TextSaveImagesAs {
            get {
                return ResourceManager.GetString("TextSaveImagesAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Select files 的當地語系化字串。
        /// </summary>
        public static string TextSelectFiles {
            get {
                return ResourceManager.GetString("TextSelectFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Game Resource browser 的當地語系化字串。
        /// </summary>
        public static string TextTitle {
            get {
                return ResourceManager.GetString("TextTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Application update 的當地語系化字串。
        /// </summary>
        public static string TextUpdateTitle {
            get {
                return ResourceManager.GetString("TextUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Image viewer 的當地語系化字串。
        /// </summary>
        public static string TextViewer {
            get {
                return ResourceManager.GetString("TextViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Visit download page 的當地語系化字串。
        /// </summary>
        public static string TextVisitPage {
            get {
                return ResourceManager.GetString("TextVisitPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Either WAV, MP3 or OGG 的當地語系化字串。
        /// </summary>
        public static string TooltipAudioFormats {
            get {
                return ResourceManager.GetString("TooltipAudioFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Back 的當地語系化字串。
        /// </summary>
        public static string TooltipBack {
            get {
                return ResourceManager.GetString("TooltipBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Forward 的當地語系化字串。
        /// </summary>
        public static string TooltipForward {
            get {
                return ResourceManager.GetString("TooltipForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;DIR&gt; 的當地語系化字串。
        /// </summary>
        public static string Type_directory {
            get {
                return ResourceManager.GetString("Type_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 none 的當地語系化字串。
        /// </summary>
        public static string Type_NONE {
            get {
                return ResourceManager.GetString("Type_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Scale large images to fit window 的當地語系化字串。
        /// </summary>
        public static string winDownScaleImage {
            get {
                return ResourceManager.GetString("winDownScaleImage", resourceCulture);
            }
        }
    }
}
